### PR TITLE
Edited SQL query

### PR DESCRIPTION
**Pull request by mizhgan**
Added "if exists" to SQL query in order to fresh installation be possible.

### CODE REVIEW

**Comment by xnaas** [comment]
Was wondering why I couldn't spin this up to test... 🙃

**Comment by nbr23** [comment]
Oups, my bad, thanks @mizhgan, and sorry for the trouble @xnaas  !
Commit cherry picked and pushed to master :)

**Comment by xnaas** [comment]
Hmm...running the newest Docker, I'm still running into the same issue.

Logs:

```
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl       | Outdated jbos table, cleaning up and recreating
youtubedl       | Traceback (most recent call last):
youtubedl       |   File "./youtube-dl-server.py", line 108, in <module>
youtubedl       |     JobsDB.check_db_latest()
youtubedl       |   File "/usr/src/app/ydl_server/logdb.py", line 64, in check_db_latest
youtubedl       |     cursor.execute("DROP TABLE jobs;")
youtubedl       | sqlite3.OperationalError: no such table: jobs
youtubedl exited with code 1
```

**Comment by nbr23** [comment]
Good to hear, thanks for the update :)

**Comment by nbr23** [comment]
@xnaas If you were pulling from docker hub, it looks like the latest build had failed (I believe this was on dockerhub's end, after a few retries it built successfully), so you'd have been pulling the older build.

**Pull request closed without merging**
